//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutSource.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OutSourceEntities : DbContext
    {
        public OutSourceEntities()
            : base("name=OutSourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssesLetter> AssesLetter { get; set; }
        public virtual DbSet<Creater> Creater { get; set; }
        public virtual DbSet<Read> Read { get; set; }
        public virtual DbSet<Receiver> Receiver { get; set; }
        public virtual DbSet<Work> Work { get; set; }
        public virtual DbSet<Working> Working { get; set; }
        public virtual DbSet<OutSourceCase> OutSourceCase { get; set; }
        public virtual DbSet<Apply> Apply { get; set; }
        public virtual DbSet<FileUpload_DB_Certif> FileUpload_DB_Certif { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
