CREATE TABLE [dbo].[Read]
(
	[CaseId] INT NOT NULL,
	[Id] INT NOT NULL,
	[ViewTime] VARCHAR (64) NOT NULL,
	[Interst] NVARCHAR(16) NOT NULL,
	CONSTRAINT [PK_Read] PRIMARY KEY CLUSTERED 
	(
	[CaseId],
	[Id]
	) ON [PRIMARY] 
) 
