CREATE TABLE [dbo].[Users]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR (64)  NOT NULL,
	[CellPhone] NVARCHAR (20) NOT NULL,
	[Email] NVARCHAR (20) NOT NULL,
	[Pwd] NVARCHAR (64)  NOT NULL,
	[City] NVARCHAR (64) NOT NULL,
	[Address] NVARCHAR (256) NOT NULL,
	[Birth] datetime NOT NULL, 



	

)
